const CREATE_TABLE = "CREATE TABLE";

const OPEN_PARANTHESIS = " (";

const CLOSE_PARANTHESIS = " )";

module.exports = {
    CREATE_TABLE: CREATE_TABLE,
    OPEN_PARANTHESIS: OPEN_PARANTHESIS,
    CLOSE_PARANTHESIS: CLOSE_PARANTHESIS
}