const CREATE_TABLE = "CREATE TABLE ";

const OPEN_PARANTHESIS = " (";

const CLOSE_PARANTHESIS = " )";

const INSERT = "INSERT INTO ";

const VALUES = " VALUES";

module.exports = {
    CREATE_TABLE: CREATE_TABLE,
    OPEN_PARANTHESIS: OPEN_PARANTHESIS,
    CLOSE_PARANTHESIS: CLOSE_PARANTHESIS,
    INSERT: INSERT,
    VALUES: VALUES
}